language: c
sudo: required
script: bash -ex .travis-ci.sh
os:
- linux
env:
- OCAML_VERSION=4.02
before_install:
- openssl aes-256-cbc -K $encrypted_cffc400c9eab_key -iv $encrypted_cffc400c9eab_iv
  -in .travis/gh-js.enc -out gh-js -d

after_script:
  - eval "$(ssh-agent -s)"
  - chmod 600 gh-js
  - ssh-add gh-js
  - git clone git@github.com:Engil/reason-web-toplevel.git deploy
  - cd deploy
  - git checkout gh-pages
  - cp ../toplevel/*.js ../toplevel/*.html ../toplevel/*.png .
  - git add *.js *.html *.png
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis"
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push origin gh-pages